spring:
  profiles:
    active: dev
  flyway:
    enabled: false
doma:
  dialect: postgres

---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/bookmanager
    username: testman
    password: testpass
    driverClassName: org.postgresql.Driver

---
spring:
  profiles: production
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bookmanager}
    username: ${DB_USERNAME:testman}
    password: ${DB_PASSWORD:testpass}
    driverClassName: org.postgresql.Driver
